<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <UserSecretsId>aa81f35f-a183-45f3-8ac7-083c3d425f1c</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.7" />
      <PackageReference Include="OpenAI.API" Version="1.0.0" />
    </ItemGroup>

</Project>
